# Site settings
title: Jan Milosh
email: janmilosh@gmail.com
description: "Python, JavaScript"
baseurl: "portfolio-jekyll"
url: "https://janmilosh.github.io/portfolio-jekyll"
twitter_username: janmilosh
github_username:  janmilosh
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title.html
